databases:
  - name: coders-hub-db
    databaseName: coders_hub_db
    user: coders_hub_db_user

services:
  - type: web
    name: Coders-Hub
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coders-hub-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false